use crate::windows_device_contract::{load_windows_device_contract, WindowsDeviceContractDevice};
use anyhow::{bail, Result};
use std::path::Path;

#[derive(Debug, Default, Clone)]
pub struct GuestToolsDevicesCmdServiceOverrides {
    pub virtio_blk_service: Option<String>,
    pub virtio_net_service: Option<String>,
    pub virtio_input_service: Option<String>,
    pub virtio_snd_service: Option<String>,
    pub aero_gpu_service: Option<String>,
}

fn hwids_from_patterns(patterns: &[String]) -> Result<Vec<String>> {
    if patterns.is_empty() {
        bail!("device has no hardware_id_patterns");
    }

    // Keep ordering stable and identical to the contract file. The repo copy of
    // `guest-tools/config/devices.cmd` is generated by
    // `scripts/generate-guest-tools-devices-cmd.py`, which preserves the JSON order.
    let mut out = Vec::with_capacity(patterns.len());
    for p in patterns {
        if p.is_empty() {
            bail!("device has empty hardware_id_patterns entry");
        }
        if p.contains('"') {
            bail!("hardware_id_patterns entries must not contain double quotes: {p:?}");
        }
        out.push(p.clone());
    }
    Ok(out)
}

fn quote_cmd_list(items: &[String]) -> String {
    items
        .iter()
        .map(|s| format!("\"{s}\""))
        .collect::<Vec<_>>()
        .join(" ")
}

fn device_by_name<'a>(
    contract_path: &Path,
    devices: &'a [WindowsDeviceContractDevice],
    name: &str,
) -> Result<&'a WindowsDeviceContractDevice> {
    devices
        .iter()
        .find(|d| d.device.eq_ignore_ascii_case(name))
        .ok_or_else(|| {
            anyhow::anyhow!(
                "{} is missing required device entry: {name}",
                contract_path.display()
            )
        })
}

pub fn generate_guest_tools_devices_cmd_bytes(contract_path: &Path) -> Result<Vec<u8>> {
    generate_guest_tools_devices_cmd_bytes_with_overrides(
        contract_path,
        &GuestToolsDevicesCmdServiceOverrides::default(),
    )
}

pub fn generate_guest_tools_devices_cmd_bytes_with_overrides(
    contract_path: &Path,
    overrides: &GuestToolsDevicesCmdServiceOverrides,
) -> Result<Vec<u8>> {
    let contract = load_windows_device_contract(contract_path)?;
    let contract_name = contract.contract_name.trim();
    let contract_version = contract.contract_version.trim();

    let virtio_blk = device_by_name(contract_path, &contract.devices, "virtio-blk")?;
    let virtio_net = device_by_name(contract_path, &contract.devices, "virtio-net")?;
    let virtio_snd = device_by_name(contract_path, &contract.devices, "virtio-snd")?;
    let virtio_input = device_by_name(contract_path, &contract.devices, "virtio-input")?;
    let aero_gpu = device_by_name(contract_path, &contract.devices, "aero-gpu")?;

    let virtio_blk_hwids = hwids_from_patterns(&virtio_blk.hardware_id_patterns)?;
    let virtio_net_hwids = hwids_from_patterns(&virtio_net.hardware_id_patterns)?;
    let virtio_snd_hwids = hwids_from_patterns(&virtio_snd.hardware_id_patterns)?;
    let virtio_input_hwids = hwids_from_patterns(&virtio_input.hardware_id_patterns)?;
    let aero_gpu_hwids = hwids_from_patterns(&aero_gpu.hardware_id_patterns)?;

    let stor_service = overrides
        .virtio_blk_service
        .as_deref()
        .unwrap_or(virtio_blk.driver_service_name.trim())
        .trim();
    if stor_service.is_empty() {
        bail!("virtio-blk entry has empty driver_service_name");
    }

    let net_service = overrides
        .virtio_net_service
        .as_deref()
        .unwrap_or(virtio_net.driver_service_name.trim())
        .trim();
    let snd_service = overrides
        .virtio_snd_service
        .as_deref()
        .unwrap_or(virtio_snd.driver_service_name.trim())
        .trim();
    let input_service = overrides
        .virtio_input_service
        .as_deref()
        .unwrap_or(virtio_input.driver_service_name.trim())
        .trim();
    let gpu_service = overrides
        .aero_gpu_service
        .as_deref()
        .unwrap_or(aero_gpu.driver_service_name.trim())
        .trim();

    let mut out = String::new();
    out.push_str("@echo off\r\n");
    out.push_str("rem -----------------------------------------------------------------------------\r\n");
    out.push_str("rem GENERATED FILE - DO NOT EDIT MANUALLY\r\n");
    out.push_str("rem\r\n");
    out.push_str("rem Source of truth: Windows device contract JSON\r\n");
    out.push_str("rem Generator: scripts/generate-guest-tools-devices-cmd.py\r\n");
    if !contract_name.is_empty() {
        out.push_str(&format!("rem Contract name: {contract_name}\r\n"));
    }
    out.push_str(&format!(
        "rem Contract schema_version: {}\r\n",
        contract.schema_version
    ));
    if !contract_version.is_empty() {
        out.push_str(&format!("rem Contract version: {contract_version}\r\n"));
    }
    out.push_str("rem -----------------------------------------------------------------------------\r\n");
    out.push_str("\r\n");
    out.push_str("rem This file is sourced by guest-tools\\setup.cmd and guest-tools\\uninstall.cmd.\r\n");
    out.push_str("\r\n");
    out.push_str("rem ---------------------------\r\n");
    out.push_str("rem Boot-critical storage (virtio-blk)\r\n");
    out.push_str("rem ---------------------------\r\n");
    out.push_str("\r\n");
    out.push_str(&format!("set \"AERO_VIRTIO_BLK_SERVICE={stor_service}\"\r\n"));
    out.push_str("set \"AERO_VIRTIO_BLK_SYS=\"\r\n");
    out.push_str(&format!(
        "set AERO_VIRTIO_BLK_HWIDS={}\r\n",
        quote_cmd_list(&virtio_blk_hwids)
    ));
    out.push_str("\r\n");
    out.push_str("rem ---------------------------\r\n");
    out.push_str("rem Non-boot-critical devices (used by verify.ps1)\r\n");
    out.push_str("rem ---------------------------\r\n");
    out.push_str("\r\n");
    out.push_str(&format!("set \"AERO_VIRTIO_NET_SERVICE={net_service}\"\r\n"));
    out.push_str(&format!(
        "set AERO_VIRTIO_NET_HWIDS={}\r\n",
        quote_cmd_list(&virtio_net_hwids)
    ));
    out.push_str(&format!("set \"AERO_VIRTIO_INPUT_SERVICE={input_service}\"\r\n"));
    out.push_str(&format!(
        "set AERO_VIRTIO_INPUT_HWIDS={}\r\n",
        quote_cmd_list(&virtio_input_hwids)
    ));
    out.push_str(&format!("set \"AERO_VIRTIO_SND_SERVICE={snd_service}\"\r\n"));
    out.push_str("set \"AERO_VIRTIO_SND_SYS=\"\r\n");
    out.push_str(&format!(
        "set AERO_VIRTIO_SND_HWIDS={}\r\n",
        quote_cmd_list(&virtio_snd_hwids)
    ));
    out.push_str("rem\r\n");
    out.push_str("rem AeroGPU HWIDs:\r\n");
    out.push_str("rem   - PCI\\VEN_A3A0&DEV_0001  (canonical / current)\r\n");
    out.push_str("rem   - PCI\\VEN_1AED&DEV_0001  (legacy bring-up ABI; emulator/aerogpu-legacy)\r\n");
    out.push_str("rem The Win7 driver package includes INFs for both; Guest Tools should accept either.\r\n");
    out.push_str(&format!("set \"AERO_GPU_SERVICE={gpu_service}\"\r\n"));
    out.push_str(&format!(
        "set AERO_GPU_HWIDS={}\r\n",
        quote_cmd_list(&aero_gpu_hwids)
    ));
    out.push_str("\r\n");

    Ok(out.into_bytes())
}
