name: Setup Rust
description: Install a Rust toolchain + optional targets/components, configure caching, and expose Cargo.lock policy.

inputs:
  toolchain:
    description: Rust toolchain to install (stable -> rust-toolchain.toml pin, nightly -> scripts/toolchains.json pin, or an explicit toolchain like 1.92.0 / nightly-YYYY-MM-DD).
    required: false
    default: stable
  targets:
    description: Rust targets to install (comma-separated or whitespace-delimited).
    required: false
    default: ""
  components:
    description: Rust components to install (comma-separated or whitespace-delimited).
    required: false
    default: ""
  cache:
    description: Enable caching via Swatinem/rust-cache@v2.
    required: false
    default: "true"
  locked:
    description: Cargo.lock policy (auto, always, never).
    required: false
    default: always

outputs:
  cargo_locked_flag:
    description: Either '--locked' or an empty string (per Cargo.lock policy).
    value: ${{ steps.cargo-locked.outputs.cargo_locked_flag }}
  rust_toolchain:
    description: Resolved Rust toolchain string installed by this action.
    value: ${{ steps.toolchain.outputs.toolchain }}

runs:
  using: composite
  steps:
    - name: Rust setup inputs
      env:
        INPUT_TOOLCHAIN: ${{ inputs.toolchain }}
        INPUT_TARGETS: ${{ inputs.targets }}
        INPUT_COMPONENTS: ${{ inputs.components }}
        INPUT_CACHE: ${{ inputs.cache }}
        INPUT_LOCKED: ${{ inputs.locked }}
      run: node "${{ github.action_path }}/log-inputs.mjs"

    - name: Resolve toolchain
      id: toolchain
      env:
        INPUT_TOOLCHAIN: ${{ inputs.toolchain }}
      run: node "${{ github.action_path }}/resolve-toolchain.mjs"

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ steps.toolchain.outputs.toolchain }}
        targets: ${{ inputs.targets }}
        components: ${{ inputs.components }}

    - name: Rust cache
      if: inputs.cache == 'true'
      uses: Swatinem/rust-cache@v2

    - name: Determine Cargo.lock flag
      id: cargo-locked
      env:
        INPUT_LOCKED: ${{ inputs.locked }}
      run: node "${{ github.action_path }}/cargo-locked-flag.mjs"

    - name: Rust versions
      run: node "${{ github.action_path }}/print-versions.mjs"
