@rem SPDX-License-Identifier: MIT OR Apache-2.0
@echo off
setlocal EnableExtensions

rem Signs the Aero virtio-snd driver package with a test certificate.
rem
rem Expects:
rem   cert\aero-virtio-snd-test.pfx
rem   inf\virtiosnd.sys (contract) and/or inf\virtiosnd_legacy.sys (legacy)
rem   matching catalog(s) generated by scripts\make-cat.cmd
rem
rem Usage:
rem   sign-driver.cmd [contract|legacy|all] [PFX_PASSWORD]
rem
rem Backwards compatible: if the first argument is not a variant, it is treated
rem as the PFX password:
rem   sign-driver.cmd mypassword
rem
rem Alternatively set:
rem   set PFX_PASSWORD=...

set SCRIPT_DIR=%~dp0
for %%I in ("%SCRIPT_DIR%..") do set ROOT_DIR=%%~fI
set INF_DIR=%ROOT_DIR%\inf

set CONTRACT_SYS=%INF_DIR%\virtiosnd.sys
set CONTRACT_CAT=%INF_DIR%\aero-virtio-snd.cat

set TRANS_SYS=%INF_DIR%\virtiosnd_legacy.sys
set TRANS_CAT=%INF_DIR%\aero-virtio-snd-legacy.cat

set ALIAS_INF=%INF_DIR%\virtio-snd.inf
set ALIAS_CAT=%INF_DIR%\virtio-snd.cat

set PFX_FILE=%ROOT_DIR%\cert\aero-virtio-snd-test.pfx

set VARIANT=contract
set PASS_ARG=%~1

if /I "%~1"=="contract" (
  set VARIANT=contract
  set PASS_ARG=%~2
) else if /I "%~1"=="legacy" (
  set VARIANT=legacy
  set PASS_ARG=%~2
) else if /I "%~1"=="all" (
  set VARIANT=all
  set PASS_ARG=%~2
)

if not exist "%PFX_FILE%" (
  echo ERROR: PFX not found: "%PFX_FILE%"
  echo        Run: powershell -ExecutionPolicy Bypass -File "%SCRIPT_DIR%make-cert.ps1"
  exit /b 1
)

where signtool.exe >nul 2>nul
if errorlevel 1 (
  echo ERROR: signtool.exe not found in PATH.
  echo        Install WDK 7.1 or WDK 10 and run this from a WDK Developer Command Prompt.
  exit /b 1
)

if /I "%VARIANT%"=="contract" (
  if not exist "%CONTRACT_SYS%" (
    echo ERROR: Driver binary not found: "%CONTRACT_SYS%"
    echo        Build the driver and copy virtiosnd.sys into the inf\ directory.
    exit /b 1
  )
  if not exist "%CONTRACT_CAT%" (
    echo ERROR: Catalog not found: "%CONTRACT_CAT%"
    echo        Run: "%SCRIPT_DIR%make-cat.cmd"
    exit /b 1
  )
  if exist "%ALIAS_INF%" (
    if not exist "%ALIAS_CAT%" (
      echo ERROR: Catalog not found: "%ALIAS_CAT%"
      echo        Run: "%SCRIPT_DIR%make-cat.cmd"
      exit /b 1
    )
  )
) else if /I "%VARIANT%"=="legacy" (
  if not exist "%TRANS_SYS%" (
    echo ERROR: Driver binary not found: "%TRANS_SYS%"
    echo        Build the driver (Configuration=Legacy) and copy virtiosnd_legacy.sys into the inf\ directory.
    exit /b 1
  )
  if not exist "%TRANS_CAT%" (
    echo ERROR: Catalog not found: "%TRANS_CAT%"
    echo        Run: "%SCRIPT_DIR%make-cat.cmd legacy"
    exit /b 1
  )
) else (
  rem all
  if not exist "%CONTRACT_SYS%" (
    echo ERROR: Driver binary not found: "%CONTRACT_SYS%"
    exit /b 1
  )
  if not exist "%TRANS_SYS%" (
    echo ERROR: Driver binary not found: "%TRANS_SYS%"
    exit /b 1
  )
  if not exist "%CONTRACT_CAT%" (
    echo ERROR: Catalog not found: "%CONTRACT_CAT%"
    exit /b 1
  )
  if not exist "%TRANS_CAT%" (
    echo ERROR: Catalog not found: "%TRANS_CAT%"
    exit /b 1
  )
  if exist "%ALIAS_INF%" (
    if not exist "%ALIAS_CAT%" (
      echo ERROR: Catalog not found: "%ALIAS_CAT%"
      exit /b 1
    )
  )
)

if defined PFX_PASSWORD (
  set SIGN_PFX_PASS=%PFX_PASSWORD%
) else (
  if "%PASS_ARG%"=="" (
    set /p SIGN_PFX_PASS=Enter PFX password:
  ) else (
    set SIGN_PFX_PASS=%PASS_ARG%
  )
)

if "%SIGN_PFX_PASS%"=="" (
  echo ERROR: PFX password is required.
  exit /b 1
)

echo.
echo == Signing driver package ==
echo PFX: "%PFX_FILE%"
echo Variant: "%VARIANT%"
echo.

rem For maximum Windows 7 SP1 compatibility, use SHA1 file digests for test signing.
if /I "%VARIANT%"=="contract" (
  signtool.exe sign /v /fd SHA1 /f "%PFX_FILE%" /p "%SIGN_PFX_PASS%" "%CONTRACT_SYS%"
  if errorlevel 1 (
    echo ERROR: Failed to sign SYS: "%CONTRACT_SYS%"
    exit /b 1
  )
  signtool.exe sign /v /fd SHA1 /f "%PFX_FILE%" /p "%SIGN_PFX_PASS%" "%CONTRACT_CAT%"
  if errorlevel 1 (
    echo ERROR: Failed to sign CAT: "%CONTRACT_CAT%"
    exit /b 1
  )
  if exist "%ALIAS_CAT%" (
    signtool.exe sign /v /fd SHA1 /f "%PFX_FILE%" /p "%SIGN_PFX_PASS%" "%ALIAS_CAT%"
    if errorlevel 1 (
      echo ERROR: Failed to sign CAT: "%ALIAS_CAT%"
      exit /b 1
    )
  )
) else if /I "%VARIANT%"=="legacy" (
  signtool.exe sign /v /fd SHA1 /f "%PFX_FILE%" /p "%SIGN_PFX_PASS%" "%TRANS_SYS%"
  if errorlevel 1 (
    echo ERROR: Failed to sign SYS: "%TRANS_SYS%"
    exit /b 1
  )
  signtool.exe sign /v /fd SHA1 /f "%PFX_FILE%" /p "%SIGN_PFX_PASS%" "%TRANS_CAT%"
  if errorlevel 1 (
    echo ERROR: Failed to sign CAT: "%TRANS_CAT%"
    exit /b 1
  )
) else (
  rem all
  signtool.exe sign /v /fd SHA1 /f "%PFX_FILE%" /p "%SIGN_PFX_PASS%" "%CONTRACT_SYS%"
  if errorlevel 1 (
    echo ERROR: Failed to sign SYS: "%CONTRACT_SYS%"
    exit /b 1
  )
  signtool.exe sign /v /fd SHA1 /f "%PFX_FILE%" /p "%SIGN_PFX_PASS%" "%TRANS_SYS%"
  if errorlevel 1 (
    echo ERROR: Failed to sign SYS: "%TRANS_SYS%"
    exit /b 1
  )
  signtool.exe sign /v /fd SHA1 /f "%PFX_FILE%" /p "%SIGN_PFX_PASS%" "%CONTRACT_CAT%"
  if errorlevel 1 (
    echo ERROR: Failed to sign CAT: "%CONTRACT_CAT%"
    exit /b 1
  )
  signtool.exe sign /v /fd SHA1 /f "%PFX_FILE%" /p "%SIGN_PFX_PASS%" "%TRANS_CAT%"
  if errorlevel 1 (
    echo ERROR: Failed to sign CAT: "%TRANS_CAT%"
    exit /b 1
  )
  if exist "%ALIAS_CAT%" (
    signtool.exe sign /v /fd SHA1 /f "%PFX_FILE%" /p "%SIGN_PFX_PASS%" "%ALIAS_CAT%"
    if errorlevel 1 (
      echo ERROR: Failed to sign CAT: "%ALIAS_CAT%"
      exit /b 1
    )
  )
)

echo.
echo OK: Signed SYS and catalog(s).
exit /b 0

