[CmdletBinding()]
param(
  # Path to the built guest tool (aero-virtio-selftest.exe)
  [Parameter(Mandatory = $true)]
  [string]$SelftestExePath,

  # Directory containing the Aero virtio driver .inf files (recursively copied onto the provisioning media).
  # This is intentionally flexible: it can point at a build output directory or an extracted driver package.
  [Parameter(Mandatory = $true)]
  [string]$DriversDir,

  # Output directory for provisioning media contents (always generated).
  [Parameter(Mandatory = $false)]
  [string]$OutputDir = "./out/aero-win7-provisioning",

  # If provided, attempt to build an ISO at this path (requires oscdimg or mkisofs/genisoimage).
  [Parameter(Mandatory = $false)]
  [string]$OutputIsoPath = "",

  # Default args baked into the provisioning script (expected by the host harness).
  [Parameter(Mandatory = $false)]
  [string]$HttpUrl = "http://10.0.2.2:18080/aero-virtio-selftest",

  [Parameter(Mandatory = $false)]
  [string]$DnsHost = "host.lan",

  # Optional: bake a fixed virtio-blk test directory into the scheduled task.
  # Example: "D:\\aero-virtio-selftest\\"
  [Parameter(Mandatory = $false)]
  [string]$BlkRoot = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-TextFileUtf8NoBom {
  param([Parameter(Mandatory = $true)][string]$Path, [Parameter(Mandatory = $true)][string]$Content)
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

$SelftestExePath = (Resolve-Path -LiteralPath $SelftestExePath).Path
$DriversDir = (Resolve-Path -LiteralPath $DriversDir).Path

New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null

$markerPath = Join-Path $OutputDir "AERO_PROVISIONING_MEDIA.TXT"
Write-TextFileUtf8NoBom -Path $markerPath -Content @"
This media was generated by drivers/windows7/tests/host-harness/New-AeroWin7TestImage.ps1

It is intended to be attached to a Windows 7 VM and used to provision:
- Aero virtio drivers
- aero-virtio-selftest.exe
- Task Scheduler auto-run at boot (SYSTEM)
"@

$selftestDir = Join-Path $OutputDir "AERO/selftest"
$driversOutDir = Join-Path $OutputDir "AERO/drivers"
$provisionDir = Join-Path $OutputDir "AERO/provision"

New-Item -ItemType Directory -Path $selftestDir -Force | Out-Null
New-Item -ItemType Directory -Path $driversOutDir -Force | Out-Null
New-Item -ItemType Directory -Path $provisionDir -Force | Out-Null

Copy-Item -LiteralPath $SelftestExePath -Destination (Join-Path $selftestDir "aero-virtio-selftest.exe") -Force
Copy-Item -LiteralPath $DriversDir -Destination $driversOutDir -Recurse -Force

$blkArg = ""
if (-not [string]::IsNullOrEmpty($BlkRoot)) {
  $blkArg = " --blk-root $BlkRoot"
}

$provisionCmd = @"
@echo off
setlocal enableextensions enabledelayedexpansion

set LOG=C:\aero-win7-provision.log
echo [AERO] provision start > "%LOG%"

REM Locate the provisioning media by searching drive letters for the marker file.
set MEDIA=
for %%D in (D E F G H I J K L M N O P Q R S T U V W X Y Z) do (
  if exist %%D:\AERO_PROVISIONING_MEDIA.TXT set MEDIA=%%D:
)

if "%MEDIA%"=="" (
  echo [AERO] ERROR: provisioning media not found >> "%LOG%"
  exit /b 1
)

echo [AERO] MEDIA=%MEDIA% >> "%LOG%"

REM Install drivers (all .inf files under AERO\drivers).
echo [AERO] installing drivers... >> "%LOG%"
for /r "%MEDIA%\AERO\drivers" %%F in (*.inf) do (
  echo [AERO] pnputil -i -a "%%F" >> "%LOG%"
  pnputil -i -a "%%F" >> "%LOG%" 2>&1
)

REM Install selftest binary.
mkdir C:\AeroTests >> "%LOG%" 2>&1
copy /y "%MEDIA%\AERO\selftest\aero-virtio-selftest.exe" C:\AeroTests\ >> "%LOG%" 2>&1

REM Configure auto-run on boot (runs as SYSTEM).
schtasks /Create /F /TN "AeroVirtioSelftest" /SC ONSTART /RU SYSTEM ^
  /TR "\"C:\AeroTests\aero-virtio-selftest.exe\" --http-url $HttpUrl --dns-host $DnsHost$blkArg" >> "%LOG%" 2>&1

echo [AERO] provision done >> "%LOG%"
exit /b 0
"@

Write-TextFileUtf8NoBom -Path (Join-Path $provisionDir "provision.cmd") -Content $provisionCmd

$readme = @"
Provisioning instructions (Windows 7 guest)
===========================================

This media contains:
- AERO\selftest\aero-virtio-selftest.exe
- AERO\drivers\... (driver .inf files)
- AERO\provision\provision.cmd

To provision an already-installed Windows 7 image:
1) Boot the VM (any disk/NIC is fine for this step).
2) Attach this media as a CD-ROM.
3) Run (as Administrator):

   <CD>:\AERO\provision\provision.cmd

The script will:
- Install all driver .inf files via pnputil
- Copy the selftest to C:\AeroTests\
- Create a scheduled task (SYSTEM, ONSTART) that runs the selftest each boot.

After reboot, the host harness can boot the VM and parse PASS/FAIL from COM1 serial.

Notes:
- The virtio-blk selftest requires a usable/mounted virtio volume. If your VM boots from a non-virtio disk,
  consider attaching a separate virtio data disk with a drive letter and using the selftest option `--blk-root`.
"@

Write-TextFileUtf8NoBom -Path (Join-Path $OutputDir "README.txt") -Content $readme

Write-Host "Generated provisioning directory: $OutputDir"

if (-not [string]::IsNullOrEmpty($OutputIsoPath)) {
  $isoParent = Split-Path -Parent $OutputIsoPath
  if ([string]::IsNullOrEmpty($isoParent)) { $isoParent = "." }
  if (-not (Test-Path -LiteralPath $isoParent)) {
    New-Item -ItemType Directory -Path $isoParent -Force | Out-Null
  }
  $OutputIsoPath = Join-Path (Resolve-Path -LiteralPath $isoParent).Path (Split-Path -Leaf $OutputIsoPath)

  $oscdimg = Get-Command oscdimg -ErrorAction SilentlyContinue
  $mkisofs = Get-Command mkisofs -ErrorAction SilentlyContinue
  $genisoimage = Get-Command genisoimage -ErrorAction SilentlyContinue

  if ($oscdimg) {
    Write-Host "Building ISO via oscdimg: $OutputIsoPath"
    & $oscdimg.Source "-n" "-m" $OutputDir $OutputIsoPath
  } elseif ($mkisofs) {
    Write-Host "Building ISO via mkisofs: $OutputIsoPath"
    & $mkisofs.Source "-quiet" "-o" $OutputIsoPath "-J" "-r" $OutputDir
  } elseif ($genisoimage) {
    Write-Host "Building ISO via genisoimage: $OutputIsoPath"
    & $genisoimage.Source "-quiet" "-o" $OutputIsoPath "-J" "-r" $OutputDir
  } else {
    Write-Warning "OutputIsoPath specified, but no ISO tool found (oscdimg/mkisofs/genisoimage)."
    Write-Warning "You can still attach the directory contents via your preferred ISO creation tool."
  }
}
