#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Opcode {
    Nop,
    Mov,
    Add,
    Mul,
    Mad,
    Dp3,
    Dp4,
    Min,
    Max,
    Rcp,
    Rsq,
    Frc,
    Exp,
    Log,
    Lit,
    Dst,
    Cmp,
    Slt,
    Sge,
    Texkill,
    Texld,
    Texldp,
    Texldb,
    Texldd,
    Texldl,
    If,
    Else,
    EndIf,
    Loop,
    EndLoop,
    Rep,
    EndRep,
    Break,
    BreakC,
    Call,
    CallNz,
    Ret,
    Label,
    Mova,
    Setp,
}

impl Opcode {
    pub fn mnemonic(self) -> &'static str {
        match self {
            Opcode::Nop => "nop",
            Opcode::Mov => "mov",
            Opcode::Add => "add",
            Opcode::Mul => "mul",
            Opcode::Mad => "mad",
            Opcode::Dp3 => "dp3",
            Opcode::Dp4 => "dp4",
            Opcode::Min => "min",
            Opcode::Max => "max",
            Opcode::Rcp => "rcp",
            Opcode::Rsq => "rsq",
            Opcode::Frc => "frc",
            Opcode::Exp => "exp",
            Opcode::Log => "log",
            Opcode::Lit => "lit",
            Opcode::Dst => "dst",
            Opcode::Cmp => "cmp",
            Opcode::Slt => "slt",
            Opcode::Sge => "sge",
            Opcode::Texkill => "texkill",
            Opcode::Texld => "texld",
            Opcode::Texldp => "texldp",
            Opcode::Texldb => "texldb",
            Opcode::Texldd => "texldd",
            Opcode::Texldl => "texldl",
            Opcode::If => "if",
            Opcode::Else => "else",
            Opcode::EndIf => "endif",
            Opcode::Loop => "loop",
            Opcode::EndLoop => "endloop",
            Opcode::Rep => "rep",
            Opcode::EndRep => "endrep",
            Opcode::Break => "break",
            Opcode::BreakC => "breakc",
            Opcode::Call => "call",
            Opcode::CallNz => "callnz",
            Opcode::Ret => "ret",
            Opcode::Label => "label",
            Opcode::Mova => "mova",
            Opcode::Setp => "setp",
        }
    }
}

pub const OPCODE_DCL: u16 = 31;
pub const OPCODE_COMMENT: u16 = 0xFFFE;
pub const OPCODE_END: u16 = 0xFFFF;

pub fn decode_opcode(opcode_raw: u16, specific: u8) -> Option<Opcode> {
    Some(match opcode_raw {
        0 => Opcode::Nop,
        1 => Opcode::Mov,
        2 => Opcode::Add,
        4 => Opcode::Mad,
        5 => Opcode::Mul,
        6 => Opcode::Rcp,
        7 => Opcode::Rsq,
        8 => Opcode::Dp3,
        9 => Opcode::Dp4,
        10 => Opcode::Min,
        11 => Opcode::Max,
        12 => Opcode::Slt,
        13 => Opcode::Sge,
        14 => Opcode::Exp,
        15 => Opcode::Log,
        16 => Opcode::Lit,
        17 => Opcode::Dst,
        19 => Opcode::Frc,
        25 => Opcode::Call,
        26 => Opcode::CallNz,
        27 => Opcode::Loop,
        28 => Opcode::Ret,
        29 => Opcode::EndLoop,
        30 => Opcode::Label,
        38 => Opcode::Rep,
        39 => Opcode::EndRep,
        40 => Opcode::If,
        42 => Opcode::Else,
        43 => Opcode::EndIf,
        44 => Opcode::Break,
        45 => Opcode::BreakC,
        46 => Opcode::Mova,
        65 => Opcode::Texkill,
        66 => match specific {
            1 => Opcode::Texldp,
            2 => Opcode::Texldb,
            _ => Opcode::Texld,
        },
        88 => Opcode::Cmp,
        93 => Opcode::Texldd,
        94 => Opcode::Setp,
        95 => Opcode::Texldl,
        _ => return None,
    })
}
