// This file is auto-generated by tools/gen_scancodes/gen_scancodes.mjs.
// Source of truth: tools/gen_scancodes/scancodes.json
//
// Regenerate:
//   npm run gen:scancodes

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Ps2Set2Scancode {
    Simple {
        make: u8,
        extended: bool,
    },
    Sequence {
        make: &'static [u8],
        break_seq: &'static [u8],
    },
}

impl Ps2Set2Scancode {
    pub fn bytes(&self, pressed: bool) -> Vec<u8> {
        match *self {
            Ps2Set2Scancode::Simple { make, extended } => {
                if pressed {
                    if extended {
                        vec![0xE0, make]
                    } else {
                        vec![make]
                    }
                } else if extended {
                    vec![0xE0, 0xF0, make]
                } else {
                    vec![0xF0, make]
                }
            }
            Ps2Set2Scancode::Sequence { make, break_seq } => {
                if pressed {
                    make.to_vec()
                } else {
                    break_seq.to_vec()
                }
            }
        }
    }
}

const PAUSE_MAKE: [u8; 8] = [0xE1, 0x14, 0x77, 0xE1, 0xF0, 0x14, 0xF0, 0x77];
const PAUSE_BREAK: [u8; 0] = [];
const PRINT_SCREEN_MAKE: [u8; 4] = [0xE0, 0x12, 0xE0, 0x7C];
const PRINT_SCREEN_BREAK: [u8; 6] = [0xE0, 0xF0, 0x7C, 0xE0, 0xF0, 0x12];

pub fn ps2_set2_scancode_for_code(code: &str) -> Option<Ps2Set2Scancode> {
    match code {
        "AltLeft" => Some(Ps2Set2Scancode::Simple {
            make: 0x11,
            extended: false,
        }),
        "AltRight" => Some(Ps2Set2Scancode::Simple {
            make: 0x11,
            extended: true,
        }),
        "ArrowDown" => Some(Ps2Set2Scancode::Simple {
            make: 0x72,
            extended: true,
        }),
        "ArrowLeft" => Some(Ps2Set2Scancode::Simple {
            make: 0x6B,
            extended: true,
        }),
        "ArrowRight" => Some(Ps2Set2Scancode::Simple {
            make: 0x74,
            extended: true,
        }),
        "ArrowUp" => Some(Ps2Set2Scancode::Simple {
            make: 0x75,
            extended: true,
        }),
        "Backquote" => Some(Ps2Set2Scancode::Simple {
            make: 0x0E,
            extended: false,
        }),
        "Backslash" => Some(Ps2Set2Scancode::Simple {
            make: 0x5D,
            extended: false,
        }),
        "Backspace" => Some(Ps2Set2Scancode::Simple {
            make: 0x66,
            extended: false,
        }),
        "BracketLeft" => Some(Ps2Set2Scancode::Simple {
            make: 0x54,
            extended: false,
        }),
        "BracketRight" => Some(Ps2Set2Scancode::Simple {
            make: 0x5B,
            extended: false,
        }),
        "CapsLock" => Some(Ps2Set2Scancode::Simple {
            make: 0x58,
            extended: false,
        }),
        "Comma" => Some(Ps2Set2Scancode::Simple {
            make: 0x41,
            extended: false,
        }),
        "ContextMenu" => Some(Ps2Set2Scancode::Simple {
            make: 0x2F,
            extended: true,
        }),
        "ControlLeft" => Some(Ps2Set2Scancode::Simple {
            make: 0x14,
            extended: false,
        }),
        "ControlRight" => Some(Ps2Set2Scancode::Simple {
            make: 0x14,
            extended: true,
        }),
        "Delete" => Some(Ps2Set2Scancode::Simple {
            make: 0x71,
            extended: true,
        }),
        "Digit0" => Some(Ps2Set2Scancode::Simple {
            make: 0x45,
            extended: false,
        }),
        "Digit1" => Some(Ps2Set2Scancode::Simple {
            make: 0x16,
            extended: false,
        }),
        "Digit2" => Some(Ps2Set2Scancode::Simple {
            make: 0x1E,
            extended: false,
        }),
        "Digit3" => Some(Ps2Set2Scancode::Simple {
            make: 0x26,
            extended: false,
        }),
        "Digit4" => Some(Ps2Set2Scancode::Simple {
            make: 0x25,
            extended: false,
        }),
        "Digit5" => Some(Ps2Set2Scancode::Simple {
            make: 0x2E,
            extended: false,
        }),
        "Digit6" => Some(Ps2Set2Scancode::Simple {
            make: 0x36,
            extended: false,
        }),
        "Digit7" => Some(Ps2Set2Scancode::Simple {
            make: 0x3D,
            extended: false,
        }),
        "Digit8" => Some(Ps2Set2Scancode::Simple {
            make: 0x3E,
            extended: false,
        }),
        "Digit9" => Some(Ps2Set2Scancode::Simple {
            make: 0x46,
            extended: false,
        }),
        "End" => Some(Ps2Set2Scancode::Simple {
            make: 0x69,
            extended: true,
        }),
        "Enter" => Some(Ps2Set2Scancode::Simple {
            make: 0x5A,
            extended: false,
        }),
        "Equal" => Some(Ps2Set2Scancode::Simple {
            make: 0x55,
            extended: false,
        }),
        "Escape" => Some(Ps2Set2Scancode::Simple {
            make: 0x76,
            extended: false,
        }),
        "F1" => Some(Ps2Set2Scancode::Simple {
            make: 0x05,
            extended: false,
        }),
        "F10" => Some(Ps2Set2Scancode::Simple {
            make: 0x09,
            extended: false,
        }),
        "F11" => Some(Ps2Set2Scancode::Simple {
            make: 0x78,
            extended: false,
        }),
        "F12" => Some(Ps2Set2Scancode::Simple {
            make: 0x07,
            extended: false,
        }),
        "F2" => Some(Ps2Set2Scancode::Simple {
            make: 0x06,
            extended: false,
        }),
        "F3" => Some(Ps2Set2Scancode::Simple {
            make: 0x04,
            extended: false,
        }),
        "F4" => Some(Ps2Set2Scancode::Simple {
            make: 0x0C,
            extended: false,
        }),
        "F5" => Some(Ps2Set2Scancode::Simple {
            make: 0x03,
            extended: false,
        }),
        "F6" => Some(Ps2Set2Scancode::Simple {
            make: 0x0B,
            extended: false,
        }),
        "F7" => Some(Ps2Set2Scancode::Simple {
            make: 0x83,
            extended: false,
        }),
        "F8" => Some(Ps2Set2Scancode::Simple {
            make: 0x0A,
            extended: false,
        }),
        "F9" => Some(Ps2Set2Scancode::Simple {
            make: 0x01,
            extended: false,
        }),
        "Home" => Some(Ps2Set2Scancode::Simple {
            make: 0x6C,
            extended: true,
        }),
        "Insert" => Some(Ps2Set2Scancode::Simple {
            make: 0x70,
            extended: true,
        }),
        "IntlBackslash" => Some(Ps2Set2Scancode::Simple {
            make: 0x61,
            extended: false,
        }),
        "IntlHash" => Some(Ps2Set2Scancode::Simple {
            make: 0x5D,
            extended: false,
        }),
        "IntlRo" => Some(Ps2Set2Scancode::Simple {
            make: 0x61,
            extended: false,
        }),
        "IntlYen" => Some(Ps2Set2Scancode::Simple {
            make: 0x5D,
            extended: false,
        }),
        "KeyA" => Some(Ps2Set2Scancode::Simple {
            make: 0x1C,
            extended: false,
        }),
        "KeyB" => Some(Ps2Set2Scancode::Simple {
            make: 0x32,
            extended: false,
        }),
        "KeyC" => Some(Ps2Set2Scancode::Simple {
            make: 0x21,
            extended: false,
        }),
        "KeyD" => Some(Ps2Set2Scancode::Simple {
            make: 0x23,
            extended: false,
        }),
        "KeyE" => Some(Ps2Set2Scancode::Simple {
            make: 0x24,
            extended: false,
        }),
        "KeyF" => Some(Ps2Set2Scancode::Simple {
            make: 0x2B,
            extended: false,
        }),
        "KeyG" => Some(Ps2Set2Scancode::Simple {
            make: 0x34,
            extended: false,
        }),
        "KeyH" => Some(Ps2Set2Scancode::Simple {
            make: 0x33,
            extended: false,
        }),
        "KeyI" => Some(Ps2Set2Scancode::Simple {
            make: 0x43,
            extended: false,
        }),
        "KeyJ" => Some(Ps2Set2Scancode::Simple {
            make: 0x3B,
            extended: false,
        }),
        "KeyK" => Some(Ps2Set2Scancode::Simple {
            make: 0x42,
            extended: false,
        }),
        "KeyL" => Some(Ps2Set2Scancode::Simple {
            make: 0x4B,
            extended: false,
        }),
        "KeyM" => Some(Ps2Set2Scancode::Simple {
            make: 0x3A,
            extended: false,
        }),
        "KeyN" => Some(Ps2Set2Scancode::Simple {
            make: 0x31,
            extended: false,
        }),
        "KeyO" => Some(Ps2Set2Scancode::Simple {
            make: 0x44,
            extended: false,
        }),
        "KeyP" => Some(Ps2Set2Scancode::Simple {
            make: 0x4D,
            extended: false,
        }),
        "KeyQ" => Some(Ps2Set2Scancode::Simple {
            make: 0x15,
            extended: false,
        }),
        "KeyR" => Some(Ps2Set2Scancode::Simple {
            make: 0x2D,
            extended: false,
        }),
        "KeyS" => Some(Ps2Set2Scancode::Simple {
            make: 0x1B,
            extended: false,
        }),
        "KeyT" => Some(Ps2Set2Scancode::Simple {
            make: 0x2C,
            extended: false,
        }),
        "KeyU" => Some(Ps2Set2Scancode::Simple {
            make: 0x3C,
            extended: false,
        }),
        "KeyV" => Some(Ps2Set2Scancode::Simple {
            make: 0x2A,
            extended: false,
        }),
        "KeyW" => Some(Ps2Set2Scancode::Simple {
            make: 0x1D,
            extended: false,
        }),
        "KeyX" => Some(Ps2Set2Scancode::Simple {
            make: 0x22,
            extended: false,
        }),
        "KeyY" => Some(Ps2Set2Scancode::Simple {
            make: 0x35,
            extended: false,
        }),
        "KeyZ" => Some(Ps2Set2Scancode::Simple {
            make: 0x1A,
            extended: false,
        }),
        "MetaLeft" => Some(Ps2Set2Scancode::Simple {
            make: 0x1F,
            extended: true,
        }),
        "MetaRight" => Some(Ps2Set2Scancode::Simple {
            make: 0x27,
            extended: true,
        }),
        "Minus" => Some(Ps2Set2Scancode::Simple {
            make: 0x4E,
            extended: false,
        }),
        "NumLock" => Some(Ps2Set2Scancode::Simple {
            make: 0x77,
            extended: false,
        }),
        "Numpad0" => Some(Ps2Set2Scancode::Simple {
            make: 0x70,
            extended: false,
        }),
        "Numpad1" => Some(Ps2Set2Scancode::Simple {
            make: 0x69,
            extended: false,
        }),
        "Numpad2" => Some(Ps2Set2Scancode::Simple {
            make: 0x72,
            extended: false,
        }),
        "Numpad3" => Some(Ps2Set2Scancode::Simple {
            make: 0x7A,
            extended: false,
        }),
        "Numpad4" => Some(Ps2Set2Scancode::Simple {
            make: 0x6B,
            extended: false,
        }),
        "Numpad5" => Some(Ps2Set2Scancode::Simple {
            make: 0x73,
            extended: false,
        }),
        "Numpad6" => Some(Ps2Set2Scancode::Simple {
            make: 0x74,
            extended: false,
        }),
        "Numpad7" => Some(Ps2Set2Scancode::Simple {
            make: 0x6C,
            extended: false,
        }),
        "Numpad8" => Some(Ps2Set2Scancode::Simple {
            make: 0x75,
            extended: false,
        }),
        "Numpad9" => Some(Ps2Set2Scancode::Simple {
            make: 0x7D,
            extended: false,
        }),
        "NumpadAdd" => Some(Ps2Set2Scancode::Simple {
            make: 0x79,
            extended: false,
        }),
        "NumpadClear" => Some(Ps2Set2Scancode::Simple {
            make: 0x73,
            extended: false,
        }),
        "NumpadComma" => Some(Ps2Set2Scancode::Simple {
            make: 0x71,
            extended: false,
        }),
        "NumpadDecimal" => Some(Ps2Set2Scancode::Simple {
            make: 0x71,
            extended: false,
        }),
        "NumpadDivide" => Some(Ps2Set2Scancode::Simple {
            make: 0x4A,
            extended: true,
        }),
        "NumpadEnter" => Some(Ps2Set2Scancode::Simple {
            make: 0x5A,
            extended: true,
        }),
        "NumpadEqual" => Some(Ps2Set2Scancode::Simple {
            make: 0x55,
            extended: false,
        }),
        "NumpadMultiply" => Some(Ps2Set2Scancode::Simple {
            make: 0x7C,
            extended: false,
        }),
        "NumpadSubtract" => Some(Ps2Set2Scancode::Simple {
            make: 0x7B,
            extended: false,
        }),
        "OSLeft" => Some(Ps2Set2Scancode::Simple {
            make: 0x1F,
            extended: true,
        }),
        "OSRight" => Some(Ps2Set2Scancode::Simple {
            make: 0x27,
            extended: true,
        }),
        "PageDown" => Some(Ps2Set2Scancode::Simple {
            make: 0x7A,
            extended: true,
        }),
        "PageUp" => Some(Ps2Set2Scancode::Simple {
            make: 0x7D,
            extended: true,
        }),
        "Pause" => Some(Ps2Set2Scancode::Sequence {
            make: &PAUSE_MAKE,
            break_seq: &PAUSE_BREAK,
        }),
        "Period" => Some(Ps2Set2Scancode::Simple {
            make: 0x49,
            extended: false,
        }),
        "PrintScreen" => Some(Ps2Set2Scancode::Sequence {
            make: &PRINT_SCREEN_MAKE,
            break_seq: &PRINT_SCREEN_BREAK,
        }),
        "Quote" => Some(Ps2Set2Scancode::Simple {
            make: 0x52,
            extended: false,
        }),
        "ScrollLock" => Some(Ps2Set2Scancode::Simple {
            make: 0x7E,
            extended: false,
        }),
        "Semicolon" => Some(Ps2Set2Scancode::Simple {
            make: 0x4C,
            extended: false,
        }),
        "ShiftLeft" => Some(Ps2Set2Scancode::Simple {
            make: 0x12,
            extended: false,
        }),
        "ShiftRight" => Some(Ps2Set2Scancode::Simple {
            make: 0x59,
            extended: false,
        }),
        "Slash" => Some(Ps2Set2Scancode::Simple {
            make: 0x4A,
            extended: false,
        }),
        "Space" => Some(Ps2Set2Scancode::Simple {
            make: 0x29,
            extended: false,
        }),
        "Tab" => Some(Ps2Set2Scancode::Simple {
            make: 0x0D,
            extended: false,
        }),
        _ => None,
    }
}

pub fn ps2_set2_bytes_for_key_event(code: &str, pressed: bool) -> Option<Vec<u8>> {
    ps2_set2_scancode_for_code(code).map(|sc| sc.bytes(pressed))
}
