name: Setup Node workspace
description: Detect the repo's Node workspace (package.json + lockfile), setup Node with npm cache, and run npm ci.

inputs:
  node-version:
    description: Optional override Node version (defaults to <working-directory>/.nvmrc).
    required: false
    default: ""
  working-directory:
    description: Path to the repository checkout root (useful when actions/checkout uses `path:`).
    required: false
    default: "."
  skip-npm-ci:
    description: Skip `npm ci` (for workflows that only need Node to parse lockfiles).
    required: false
    default: "false"

outputs:
  dir:
    description: Resolved workspace directory (relative to GITHUB_WORKSPACE).
    value: ${{ steps.detect.outputs.dir }}
  lockfile:
    description: Resolved lockfile path (relative to GITHUB_WORKSPACE).
    value: ${{ steps.detect.outputs.lockfile }}
  node_version:
    description: Node version used by actions/setup-node.
    value: ${{ steps.node-version.outputs.node_version }}

runs:
  using: composite
  steps:
    - id: node-version
      name: Resolve Node version
      env:
        AERO_ACTION_NODE_VERSION: ${{ inputs.node-version }}
        AERO_ACTION_WORKING_DIRECTORY: ${{ inputs.working-directory }}
      run: node "${{ github.action_path }}/resolve-node-version.mjs"

    - id: detect
      name: Detect Node workspace
      env:
        AERO_ACTION_WORKING_DIRECTORY: ${{ inputs.working-directory }}
      run: node "${{ github.action_path }}/detect-node-workspace.mjs"

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.node-version.outputs.node_version }}
        cache: npm
        cache-dependency-path: ${{ steps.detect.outputs.lockfile }}

    - name: Install dependencies (npm ci)
      if: ${{ inputs.skip-npm-ci != 'true' }}
      working-directory: ${{ steps.detect.outputs.install_dir }}
      env:
        # Prevent Playwright's postinstall hook from downloading browser binaries during npm ci.
        # CI should download browsers via the dedicated `.github/actions/setup-playwright` step,
        # which enables caching and avoids flaky installs.
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
      run: npm ci
