#!/usr/bin/env python3
"""
Regenerate or check artifacts derived from `docs/windows-device-contract.json`.

This is a single "one-shot" entrypoint intended for both contributor workflows
and CI drift checks.

Derived artifacts in scope:
  - guest-tools/config/devices.cmd
      (generated by scripts/generate-guest-tools-devices-cmd.py)
  - docs/windows-device-contract-virtio-win.json
      (generated by scripts/generate-windows-device-contract-virtio-win.py)

Usage:
  # Regenerate both artifacts
  python3 scripts/regen-windows-device-contract-artifacts.py

  # Check whether both artifacts are up-to-date (no writes)
  python3 scripts/regen-windows-device-contract-artifacts.py --check
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class Artifact:
    path: Path
    generator: Path


ARTIFACTS: tuple[Artifact, ...] = (
    Artifact(
        path=REPO_ROOT / "guest-tools/config/devices.cmd",
        generator=REPO_ROOT / "scripts/generate-guest-tools-devices-cmd.py",
    ),
    Artifact(
        path=REPO_ROOT / "docs/windows-device-contract-virtio-win.json",
        generator=REPO_ROOT / "scripts/generate-windows-device-contract-virtio-win.py",
    ),
)


def _strip_generator_remediation(stderr: str) -> str:
    """
    Individual generator scripts print a remediation line pointing at themselves.

    This wrapper provides a single remediation command, so in `--check` drift mode
    we strip the generator's own footer while preserving the diff/context.
    """

    # Generators print their own footer starting with a newline + "ERROR:" at BOL.
    marker = "\nERROR:"
    idx = stderr.find(marker)
    if idx == -1:
        return stderr
    return stderr[:idx].rstrip() + "\n"


def _run_generator(*, generator: Path, check: bool) -> subprocess.CompletedProcess[str]:
    if not generator.exists():
        print(f"error: missing generator: {generator.as_posix()}", file=sys.stderr)
        raise SystemExit(2)

    cmd = [sys.executable, str(generator)]
    if check:
        cmd.append("--check")

    # Capture output so we can present unified error messages.
    return subprocess.run(
        cmd,
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
    )


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check whether artifacts are up-to-date (do not write).",
    )
    args = parser.parse_args(argv)

    if args.check:
        out_of_date: list[Artifact] = []
        for artifact in ARTIFACTS:
            proc = _run_generator(generator=artifact.generator, check=True)
            if proc.returncode == 0:
                continue

            if proc.returncode == 1:
                out_of_date.append(artifact)
                # Show the underlying diff/context, but strip the generator's own
                # remediation footer to avoid conflicting guidance.
                if proc.stdout:
                    sys.stderr.write(proc.stdout)
                if proc.stderr:
                    sys.stderr.write(_strip_generator_remediation(proc.stderr))
                continue

            # Generator failure (invalid contract JSON, missing file, etc).
            if proc.stdout:
                sys.stderr.write(proc.stdout)
            if proc.stderr:
                sys.stderr.write(proc.stderr)
            sys.stderr.write(
                f"\nERROR: generator failed (exit code {proc.returncode}): {artifact.generator.as_posix()}\n"
            )
            return proc.returncode or 2

        if out_of_date:
            sys.stderr.write("\nERROR: Windows device contract derived artifacts are out of date:\n")
            for artifact in out_of_date:
                sys.stderr.write(f"  - {artifact.path.relative_to(REPO_ROOT).as_posix()}\n")
            sys.stderr.write(
                "\nRemediation:\n"
                "  python3 scripts/regen-windows-device-contract-artifacts.py\n"
            )
            return 1
        return 0

    # Regenerate mode.
    for artifact in ARTIFACTS:
        proc = _run_generator(generator=artifact.generator, check=False)
        if proc.returncode != 0:
            if proc.stdout:
                sys.stderr.write(proc.stdout)
            if proc.stderr:
                sys.stderr.write(proc.stderr)
            sys.stderr.write(
                f"\nERROR: generator failed (exit code {proc.returncode}): {artifact.generator.as_posix()}\n"
            )
            return proc.returncode or 2

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))

