#!/usr/bin/env bash
set -euo pipefail

if ! command -v iasl >/dev/null 2>&1; then
  echo "error: iasl not found in PATH (install ACPICA iasl to verify DSDT ASL fixtures)" >&2
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "error: python3 not found in PATH (required to normalize iasl output when verifying dsdt.aml)" >&2
  exit 1
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

verify_dsdt_pair() {
  local asl_rel="$1"
  local aml_rel="$2"
  local prefix="$3"
  local allow_gen_dsdt_hint="$4"

  local asl="${ROOT_DIR}/${asl_rel}"
  local aml_expected="${ROOT_DIR}/${aml_rel}"

  # Use `-p` so verification doesn't write artifacts into the repo.
  #
  # ACPICA warns (3168) about legacy Processor() objects. Treat that warning as
  # non-fatal/noise here since we still validate the actual AML round-trip with
  # `scripts/validate-acpi.sh`.
  iasl -vw 3168 -tc -p "${tmp_dir}/${prefix}" "${asl}" >/dev/null

  local aml_generated="${tmp_dir}/${prefix}.aml"
  if [[ ! -f "${aml_generated}" ]]; then
    echo "error: expected iasl to produce ${aml_generated} when compiling ${asl_rel}" >&2
    ls -la "${tmp_dir}" >&2 || true
    exit 1
  fi

  # `iasl` stamps the "ASL compiler ID/revision" fields in the ACPI table header,
  # but our shipped fixtures are generated by `aero-acpi` and use their own creator
  # ID. These fields are not expressible in ASL, so normalize the compiled output
  # to the generator's header values and recompute the checksum before doing a
  # byte-for-byte compare.
  python3 - <<'PY' "${aml_generated}"
import sys
from pathlib import Path

path = Path(sys.argv[1])
data = bytearray(path.read_bytes())

if len(data) < 36:
    raise SystemExit(f"generated AML is unexpectedly short ({len(data)} bytes): {path}")

# ACPI SDT header layout:
#   offset 9:  Checksum (u8)
#   offset 28: CreatorId (4 bytes)
#   offset 32: CreatorRevision (u32 little-endian)
data[28:32] = b"AERO"
data[32:36] = (1).to_bytes(4, "little")

# Recompute checksum: sum of all bytes must wrap to 0.
data[9] = 0
data[9] = (-sum(data)) & 0xFF

path.write_bytes(data)
PY

  if ! cmp -s "${aml_expected}" "${aml_generated}"; then
    echo "error: ACPI DSDT drift detected: ${asl_rel} does not match ${aml_rel}" >&2
    echo "" >&2
    echo "Regenerate deterministic in-repo fixtures (preferred):" >&2
    echo "  (cd \"${ROOT_DIR}\" && cargo xtask fixtures)" >&2
    echo "" >&2
    if [[ "${allow_gen_dsdt_hint}" == "true" ]]; then
      echo "Or regenerate just the checked-in legacy PCI DSDT fixture:" >&2
      echo "  (cd \"${ROOT_DIR}\" && cargo run -p firmware --bin gen_dsdt --locked)" >&2
      echo "" >&2
    fi
    echo "If you intended to change the ACPI DSDT, update ${asl_rel} to match the regenerated fixture." >&2
    echo "" >&2
    echo "If you need a decompiled baseline to compare against, you can also run:" >&2
    echo "  (cd \"${ROOT_DIR}\" && iasl -d ${aml_rel})  # emits a .dsl file in the current directory" >&2
    echo "" >&2
    echo "Diff hint (first differing bytes):" >&2
    # `cmp -l` returns exit code 1 when files differ; ignore that.
    cmp -l "${aml_expected}" "${aml_generated}" | head -n 20 >&2 || true
    echo "" >&2

    if command -v sha256sum >/dev/null 2>&1; then
      echo "sha256sum:" >&2
      sha256sum "${aml_expected}" "${aml_generated}" >&2 || true
    else
      echo "cksum:" >&2
      cksum "${aml_expected}" "${aml_generated}" >&2 || true
    fi

    exit 1
  fi
}

verify_dsdt_pair "crates/firmware/acpi/dsdt.asl" "crates/firmware/acpi/dsdt.aml" "dsdt" "true"
verify_dsdt_pair "crates/firmware/acpi/dsdt_pcie.asl" "crates/firmware/acpi/dsdt_pcie.aml" "dsdt_pcie" "false"
