#!/usr/bin/env bash
set -euo pipefail

if ! command -v iasl >/dev/null 2>&1; then
  echo "error: iasl not found in PATH (install ACPICA iasl to verify dsdt.asl)" >&2
  exit 1
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

asl_rel="crates/firmware/acpi/dsdt.asl"
aml_rel="crates/firmware/acpi/dsdt.aml"

asl="${ROOT_DIR}/${asl_rel}"
aml_expected="${ROOT_DIR}/${aml_rel}"

# Use `-p` so verification doesn't write artifacts into the repo.
iasl -tc -p "${tmp_dir}/dsdt" "${asl}" >/dev/null

aml_generated="${tmp_dir}/dsdt.aml"
if [[ ! -f "${aml_generated}" ]]; then
  echo "error: expected iasl to produce ${aml_generated} when compiling ${asl_rel}" >&2
  ls -la "${tmp_dir}" >&2 || true
  exit 1
fi

# `iasl` stamps the "ASL compiler ID/revision" fields in the ACPI table header,
# but our shipped fixture is generated by `aero-acpi` and uses its own creator
# ID. These fields are not expressible in ASL, so normalize them (and the table
# checksum) to the shipped fixture before doing a byte-for-byte compare.
dd if="${aml_expected}" of="${aml_generated}" bs=1 skip=28 count=8 seek=28 conv=notrunc 2>/dev/null
dd if="${aml_expected}" of="${aml_generated}" bs=1 skip=9 count=1 seek=9 conv=notrunc 2>/dev/null

# Prevent drift between the human-readable ASL (`dsdt.asl`) and the shipped AML fixture (`dsdt.aml`).
if ! cmp -s "${aml_expected}" "${aml_generated}"; then
  echo "error: ACPI DSDT drift detected: ${asl_rel} does not match ${aml_rel}" >&2
  echo "" >&2
  echo "Regenerate deterministic in-repo fixtures (preferred):" >&2
  echo "  (cd \"${ROOT_DIR}\" && cargo xtask fixtures)" >&2
  echo "" >&2
  echo "Or regenerate just the checked-in DSDT fixture:" >&2
  echo "  (cd \"${ROOT_DIR}\" && cargo run -p firmware --bin gen_dsdt --locked)" >&2
  echo "" >&2
  echo "If you intended to change the ACPI DSDT, update ${asl_rel} to match the regenerated fixture." >&2
  echo "" >&2
  echo "If you need a decompiled baseline to compare against, you can also run:" >&2
  echo "  (cd \"${ROOT_DIR}\" && iasl -d ${aml_rel})  # emits dsdt.dsl in the current directory" >&2
  echo "" >&2
  echo "Diff hint (first differing bytes):" >&2
  # `cmp -l` returns exit code 1 when files differ; ignore that.
  cmp -l "${aml_expected}" "${aml_generated}" | head -n 20 >&2 || true
  echo "" >&2

  if command -v sha256sum >/dev/null 2>&1; then
    echo "sha256sum:" >&2
    sha256sum "${aml_expected}" "${aml_generated}" >&2 || true
  else
    echo "cksum:" >&2
    cksum "${aml_expected}" "${aml_generated}" >&2 || true
  fi

  exit 1
fi
