name: Setup Playwright (cached)
description: Restore/cache Playwright browser binaries and install requested browsers if needed.

inputs:
  browsers:
    description: Space-separated Playwright browsers to install (e.g. "chromium firefox").
    required: false
    default: ""
  project:
    description: Alias for `browsers` (useful when workflows talk in Playwright project names).
    required: false
    default: ""
  working-directory:
    description: Directory that contains the Playwright dependency (node_modules). Defaults to the resolved Node workspace directory.
    required: false
    default: ""
  cache-path:
    description: Directory to store Playwright browser binaries. Defaults to ~/.cache/ms-playwright (Linux/mac; overridden via PLAYWRIGHT_BROWSERS_PATH).
    required: false
    default: "~/.cache/ms-playwright"
  with-deps:
    description: Install OS dependencies on Linux via `playwright install --with-deps`. Defaults to true on Linux.
    required: false
    default: ""
  lockfile:
    description: Lockfile used to key the browser cache (e.g. package-lock.json). Defaults to the lockfile resolved from the working directory.
    required: false
    default: ""

outputs:
  cache-hit:
    description: Whether the browser cache was restored from an exact key match.
    value: ${{ steps.browser-cache.outputs.cache-hit || 'false' }}

runs:
  using: composite
  steps:
    - name: Resolve Playwright inputs
      id: vars
      env:
        INPUT_BROWSERS: ${{ inputs.browsers }}
        INPUT_PROJECT: ${{ inputs.project }}
        INPUT_WORKING_DIRECTORY: ${{ inputs.working-directory }}
        INPUT_CACHE_PATH: ${{ inputs.cache-path }}
        INPUT_LOCKFILE: ${{ inputs.lockfile }}
        INPUT_WITH_DEPS: ${{ inputs.with-deps }}
      run: node "${{ github.action_path }}/resolve-inputs.mjs"
        
    - name: Resolve Playwright CLI + version
      id: playwright
      working-directory: ${{ steps.vars.outputs.working_directory }}
      run: node "${{ github.action_path }}/resolve-cli.mjs"

    - name: Check whether browsers are already installed
      id: precheck
      env:
        PLAYWRIGHT_BROWSERS_PATH: ${{ steps.vars.outputs.cache_path }}
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "0"
        BROWSERS: ${{ steps.vars.outputs.browsers }}
        PLAYWRIGHT_CLI: ${{ steps.playwright.outputs.cli }}
      run: node "${{ github.action_path }}/precheck.mjs"

    - name: Restore Playwright browser cache
      id: browser-cache
      if: steps.precheck.outputs.missing == 'true'
      uses: actions/cache@v4
      with:
        path: ${{ steps.vars.outputs.cache_path }}
        key: ${{ runner.os }}-playwright-${{ steps.vars.outputs.browsers_key }}-${{ hashFiles(steps.vars.outputs.cache_key_file) }}
        restore-keys: |
          ${{ runner.os }}-playwright-${{ steps.vars.outputs.browsers_key }}-
          ${{ runner.os }}-playwright-

    - name: Re-check browser install after cache restore
      id: check
      if: steps.precheck.outputs.missing == 'true'
      env:
        PLAYWRIGHT_BROWSERS_PATH: ${{ steps.vars.outputs.cache_path }}
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "0"
        BROWSERS: ${{ steps.vars.outputs.browsers }}
        PLAYWRIGHT_CLI: ${{ steps.playwright.outputs.cli }}
      run: node "${{ github.action_path }}/precheck.mjs"

    - name: Install Playwright browsers
      if: steps.check.outputs.missing == 'true'
      working-directory: ${{ steps.vars.outputs.working_directory }}
      env:
        PLAYWRIGHT_BROWSERS_PATH: ${{ steps.vars.outputs.cache_path }}
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "0"
        BROWSERS: ${{ steps.vars.outputs.browsers }}
        WITH_DEPS: ${{ steps.vars.outputs.with_deps }}
        PLAYWRIGHT_CLI: ${{ steps.playwright.outputs.cli }}
      run: node "${{ github.action_path }}/install-browsers.mjs"

    - name: Playwright setup summary
      if: always()
      env:
        CACHE_HIT: ${{ steps.browser-cache.outputs.cache-hit || 'skipped' }}
        WORKING_DIRECTORY: ${{ steps.vars.outputs.working_directory }}
        CACHE_PATH: ${{ steps.vars.outputs.cache_path }}
        CACHE_KEY_FILE: ${{ steps.vars.outputs.cache_key_file }}
        BROWSERS: ${{ steps.vars.outputs.browsers }}
        PLAYWRIGHT_VERSION: ${{ steps.playwright.outputs.version }}
        NEEDS_INSTALL: ${{ steps.precheck.outputs.missing == 'true' && steps.check.outputs.missing || 'false' }}
        PLAYWRIGHT_CLI: ${{ steps.playwright.outputs.cli }}
        PLAYWRIGHT_BROWSERS_PATH: ${{ steps.vars.outputs.cache_path }}
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "0"
      run: node "${{ github.action_path }}/summary.mjs"
